### PR TITLE
Finalize copy improvements

### PR DESCRIPTION
**Pull request by oskarvu**
Closes FRO-965

### CODE REVIEW

**Comment by krzkaczor** [comment]
image

"Learn more" here point to wrong location. Can you grep source code for todos/google.com 😅

**Comment by krzkaczor** [comment]
image
here's copy lacks "space".

**Comment by yivlad** [comment]
image
I think this should say something about sUSDS instead?

**Review by krzkaczor — APPROVED** [review]

**Comment by EmilMalanczak** [comment]
shouldnt be `USDS is a new version of DAI` ?
image

**Review by EmilMalanczak — APPROVED** [review]

**Review by yivlad — APPROVED** [review]

**Pull request merged**
